// get_email_digest — read your own learning digest email summaries (daily or weekly).
//
// Read-only access to auto-generated learning summaries. Ava references her own
// digests without sending capability. Digests are auto-generated by systemd
// timers at 4am PST daily + Sunday.

import fs from 'fs';
import path from 'path';

const DIGEST_DIR = process.env.AVA_DIGEST_DIR || '/data/logs';

export default {
  name: 'get_email_digest',
  description: 'Read a learning digest email (daily or weekly). Read-only access for Ava to reference her own learning summaries.',
  inputSchema: {
    type: 'object',
    properties: {
      digest_type: {
        type: 'string',
        enum: ['daily', 'weekly'],
        description: 'Type of digest: daily (latest digest) or weekly (latest weekly trends)',
      },
    },
    required: ['digest_type'],
  },
  handler: async (args) => {
    const { digest_type } = args;

    try {
      let filename;
      if (digest_type === 'daily') {
        filename = 'learning_digest.html';
      } else if (digest_type === 'weekly') {
        filename = 'learning_weekly_trends.html';
      } else {
        return { error: `Invalid digest_type: ${digest_type}` };
      }

      const filepath = path.join(DIGEST_DIR, filename);

      if (!fs.existsSync(filepath)) {
        return { error: `Digest file not found: ${filename}` };
      }

      const content = fs.readFileSync(filepath, 'utf-8');

      // Return summary with key metrics
      const title = digest_type === 'daily' ? "Today's Learning Report" : "Weekly Trends";
      return {
        digest_type,
        title,
        content,
        file: filename,
        size_bytes: content.length,
        note: 'This is a read-only digest. Ava can reference her learning, but cannot send emails.',
      };
    } catch (error) {
      return { error: `Failed to read digest: ${error.message}` };
    }
  },
};
