"""`ava app new` — scaffold the ava-tools/1 facade INSIDE a developer's app.

The developer-side half of the connector SDK (the Shopify-CLI moment): run it
in your app's repo and get a vendored, self-contained surface file implementing
the facade spec (docs/CONNECTOR_SDK.md §5), a matching connector manifest, and
a quickstart. Deliberately NOT a pip/npm package — ~100 lines the fork owns,
no version skew; the `facade: ava-tools/1` string is the compatibility contract.

Templates carry the lessons from note-keeper's hand-written surface:
a decorator registry with JIT `access` tiers, the exact error contract
(404 unknown tool / 400 bad arguments / 5xx with a message), and framework
wire-up notes (register before your SPA catch-all; lazy-import your app).
"""
from __future__ import annotations

import os
import re

FRAMEWORKS = ("fastapi", "flask", "express", "stdlib")
_ID_RE = re.compile(r"^[a-z][a-z0-9_-]{1,31}$")

# --------------------------------------------------------------------------- #
# The shared Python core: registry + decorator + dispatch. Framework templates
# append their own route wiring under it.
# --------------------------------------------------------------------------- #
_PY_CORE = '''"""__LABEL__ — agent surface for Ava (ava-tools/1).

Curated tools an AI assistant may drive — intent-level actions, NOT your whole
REST API. Spec: docs/CONNECTOR_SDK.md §5 in the Ava repo. Generated by
`ava app new`; this file is yours — edit freely.

The `access` tier drives Ava's just-in-time consent:
    read         runs silently
    write        asks the operator on FIRST use ("Always allow" is remembered)
    destructive  asks every time, can never be always-allowed
Don't expose destructive operations you wouldn't hand an assistant — keep
deletes in your app's own UI.
"""
from __future__ import annotations

from typing import Callable

FACADE = "ava-tools/1"
TOOLS: dict[str, dict] = {}

# Served at /.well-known/ava.json so Ava's Detect can prefill its connect form.
# Add "health": "/your/health/path" and "ui": True when your app has them.
WELL_KNOWN = {"facade": FACADE, "label": "__LABEL__",
              "tools": "/tools", "call": "/call"}


def tool(name: str, description: str, params: dict | None = None,
         required: list[str] | None = None, access: str = "write"):
    """Register one agent tool. Defaults to `write` — the safe tier — so a
    forgotten annotation can only make a tool noisier, never quieter."""
    def deco(fn: Callable):
        TOOLS[name] = {
            "name": name,
            "description": description,
            "inputSchema": {"type": "object", "properties": params or {},
                            **({"required": required} if required else {}),
                            "additionalProperties": False},
            "access": access,
            "handler": fn,
        }
        return fn
    return deco


def _dispatch(name: str, args: dict) -> tuple:
    """(payload, status) per the ava-tools/1 error contract."""
    t = TOOLS.get(name)
    if not t:
        return {"error": f"unknown tool '{name}' — GET /tools lists them"}, 404
    missing = [k for k in (t["inputSchema"].get("required") or []) if k not in args]
    if missing:
        return {"error": f"bad arguments: missing {', '.join(missing)}"}, 400
    try:
        return t["handler"](args or {})
    except (TypeError, ValueError) as e:
        return {"error": f"bad arguments: {e}"}, 400
    except Exception as e:  # noqa: BLE001 — a message, never a blank 500
        return {"error": str(e)}, 500


def _listing() -> dict:
    return {"facade": FACADE,
            "tools": [{k: t[k] for k in ("name", "description", "inputSchema", "access")}
                      for t in TOOLS.values()]}


# --------------------------------------------------------------------------- #
# Your tools. Handlers take an args dict and return (payload, status).
# Call into your app lazily (import inside the handler) to avoid circular
# imports when your app module imports this file.
# --------------------------------------------------------------------------- #

@tool("ping", "Health check — returns pong.", access="read")
def _ping(args: dict) -> tuple:
    return {"pong": True}, 200


# @tool("create_note", "Create a note with the given text.",
#       {"text": {"type": "string", "description": "the note body"}},
#       required=["text"], access="write")
# def _create_note(args: dict) -> tuple:
#     import myapp                       # lazy — your app imports this file
#     note = myapp.create_note(args["text"])
#     return {"id": note.id}, 200
'''

_FASTAPI_TAIL = '''

# --------------------------------------------------------------------------- #
# FastAPI wiring — in your app:  from ava.surface import register; register(app)
# Register BEFORE any catch-all static mount (app.mount("/")) or the routes
# will be shadowed.
# --------------------------------------------------------------------------- #
# Module-level imports on purpose: `from __future__ import annotations` makes
# annotations strings, and FastAPI resolves them in module globals — a
# closure-local Request/model lands in query params instead of the body.
from fastapi import Request  # noqa: E402
from fastapi.responses import JSONResponse  # noqa: E402
from starlette.concurrency import run_in_threadpool  # noqa: E402


def register(app) -> None:
    @app.get("/.well-known/ava.json")
    def well_known():
        return WELL_KNOWN

    @app.get("/tools")
    def tools():
        return _listing()

    @app.post("/call")
    async def call(request: Request):
        try:
            body = await request.json()
        except Exception:  # noqa: BLE001
            return JSONResponse({"error": "invalid json"}, status_code=400)
        body = body if isinstance(body, dict) else {}
        # Threadpool on purpose: handlers are sync and often do blocking IO —
        # including HTTP back to THIS app. Dispatching on the event loop would
        # starve it and deadlock any self-call.
        data, status = await run_in_threadpool(
            _dispatch, str(body.get("name") or ""), body.get("arguments") or {})
        return JSONResponse(data, status_code=status)
'''

_FLASK_TAIL = '''

# --------------------------------------------------------------------------- #
# Flask wiring — in your app:  from ava.surface import bp; app.register_blueprint(bp)
# --------------------------------------------------------------------------- #
from flask import Blueprint, jsonify, request  # noqa: E402

bp = Blueprint("ava_surface", __name__)


@bp.get("/.well-known/ava.json")
def _well_known_route():
    return jsonify(WELL_KNOWN)


@bp.get("/tools")
def _tools_route():
    return jsonify(_listing())


@bp.post("/call")
def _call_route():
    body = request.get_json(silent=True) or {}
    data, status = _dispatch(str(body.get("name") or ""), body.get("arguments") or {})
    return jsonify(data), status
'''

_STDLIB_TAIL = '''

# --------------------------------------------------------------------------- #
# Standalone server (no framework): run it next to your app as a sidecar —
#   python ava/surface.py            # serves http://127.0.0.1:__PORT__
# --------------------------------------------------------------------------- #
import json
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

PORT = int(os.environ.get("__ENV_PORT__", "__PORT__"))


class _Handler(BaseHTTPRequestHandler):
    def _send(self, code: int, payload: dict) -> None:
        body = json.dumps(payload).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        path = self.path.split("?")[0]
        if path == "/health":
            return self._send(200, {"ok": True})
        if path == "/.well-known/ava.json":
            return self._send(200, {**WELL_KNOWN, "health": "/health"})
        if path == "/tools":
            return self._send(200, _listing())
        self._send(404, {"error": "not found"})

    def do_POST(self):
        if self.path.split("?")[0] != "/call":
            return self._send(404, {"error": "not found"})
        try:
            n = int(self.headers.get("Content-Length") or 0)
            body = json.loads(self.rfile.read(n) or b"{}")
        except Exception:  # noqa: BLE001
            return self._send(400, {"error": "invalid json"})
        data, status = _dispatch(str(body.get("name") or ""), body.get("arguments") or {})
        self._send(status, data)

    def log_message(self, *a):  # quiet
        pass


if __name__ == "__main__":
    print(f"[__ID__ agent surface] http://127.0.0.1:{PORT}")
    ThreadingHTTPServer(("127.0.0.1", PORT), _Handler).serve_forever()
'''

_EXPRESS_SURFACE = '''// __LABEL__ — agent surface for Ava (ava-tools/1).
// Curated tools an AI assistant may drive — intent-level actions, NOT your
// whole REST API. Spec: docs/CONNECTOR_SDK.md §5 in the Ava repo. Generated by
// `ava app new`; this file is yours — edit freely.
//
// Access tiers drive Ava's just-in-time consent:
//   read = silent · write = asks on first use (remembered) · destructive = always asks
//
// Wiring — in your app:
//   import { avaSurface } from './ava/surface.mjs';
//   app.use(avaSurface());              // BEFORE any static catch-all
import { Router, json } from 'express';

export const FACADE = 'ava-tools/1';

// Served at /.well-known/ava.json so Ava's Detect can prefill its connect form.
// Add health: '/your/health/path' and ui: true when your app has them.
export const WELL_KNOWN = { facade: FACADE, label: '__LABEL__', tools: '/tools', call: '/call' };

const TOOLS = new Map();

export function tool(name, description, inputSchema, access, handler) {
  TOOLS.set(name, { name, description,
    inputSchema: inputSchema || { type: 'object', properties: {} },
    access: access || 'write', handler });
}

// --- your tools --------------------------------------------------------------
tool('ping', 'Health check — returns pong.',
  { type: 'object', properties: {} }, 'read',
  async () => ({ pong: true }));

// tool('create_note', 'Create a note with the given text.',
//   { type: 'object', properties: { text: { type: 'string' } }, required: ['text'] },
//   'write',
//   async (args) => ({ id: await myApp.createNote(args.text) }));

// --- routes (the ava-tools/1 contract) ---------------------------------------
export function avaSurface() {
  const r = Router();
  r.use(json());
  r.get('/.well-known/ava.json', (_req, res) => res.json(WELL_KNOWN));
  r.get('/tools', (_req, res) => {
    res.json({ facade: FACADE,
      tools: [...TOOLS.values()].map(({ handler, ...t }) => t) });
  });
  r.post('/call', async (req, res) => {
    const { name, arguments: args = {} } = req.body || {};
    const t = TOOLS.get(name);
    if (!t) return res.status(404).json({ error: `unknown tool '${name}' — GET /tools lists them` });
    const missing = (t.inputSchema.required || []).filter((k) => !(k in args));
    if (missing.length) return res.status(400).json({ error: `bad arguments: missing ${missing.join(', ')}` });
    try {
      res.json(await t.handler(args));
    } catch (e) {
      res.status(500).json({ error: String(e.message || e) });  // a message, never a blank 500
    }
  });
  return r;
}
'''

_MANIFEST = '''# __LABEL__ — Ava connector manifest, generated by `ava app new`.
# Easiest path: skip this file entirely — in Ava's Hub click "Connect an app",
# paste http://127.0.0.1:__PORT__, and Detect finds the /tools facade.
# This file is for git-managed installs: drop the folder into
# $AVA_HOME/connectors/__ID__/ and restart Ava. Schema: docs/CONNECTOR_SDK.md.
id: __ID__
label: __LABEL__
kind: app
enabled: true

service:
  name: __LABEL__
  probe: "http://127.0.0.1:__PORT__/tools"   # the facade doubles as a health probe

actions:
  discover:
    base: "http://127.0.0.1:__PORT__"
    list: /tools
    call: /call
    # token_env: __ENV_TOKEN__               # uncomment if your app needs a bearer

__UI_BLOCK__'''

_UI_ON = '''# Your app's own web UI, embedded in Ava's left rail (same-origin proxy).
ui:
  label: __LABEL__
  icon: grid
  embed: iframe
  url: "http://127.0.0.1:__PORT__"
'''

_UI_OFF = '''# Uncomment to embed your app's web UI as a tile in Ava's left rail:
# ui:
#   label: __LABEL__
#   icon: grid
#   embed: iframe
#   url: "http://127.0.0.1:__PORT__"
'''

_README = '''# __LABEL__ ⇄ Ava

Generated by `ava app new __ID__ --framework __FRAMEWORK__`. Three steps:

## 1. Wire the surface into your app

__WIREUP__

## 2. Add your tools

Open `__SURFACE_FILE__` — `ping` is there as a working example. Add one
`tool(...)` per intent-level action ("generate", "list_items"), not per REST
endpoint. Pick the `access` tier honestly: `read` runs silently, `write` asks
the operator once, `destructive` asks every time. Don't expose destructive
operations you wouldn't hand an assistant.

## 3. Connect it in Ava

Open Ava's Hub -> Connectors -> **Connect an app** -> paste
`http://127.0.0.1:__PORT__` -> **Detect**. Ava finds the facade, lists your
tools, and (if your app serves a web UI) offers a sidebar tile. Sanity check
by hand: `curl http://127.0.0.1:__PORT__/tools`

Embedding your web UI in Ava's sidebar? It gets served under `/apps/__ID__/`,
so the UI must use RELATIVE asset URLs and mount-prefixed API calls — see
"Make your UI mount-agnostic" in Ava's docs/CONNECTOR_SDK.md §3.

The full contract (error shapes, tier semantics, trust boundary):
`docs/CONNECTOR_SDK.md` §5 "The tool facade — ava-tools/1" in the Ava repo.
'''

_WIREUPS = {
    "fastapi": '''```python
# in the module that builds your FastAPI app
from ava.surface import register
register(app)          # BEFORE any app.mount("/", StaticFiles(...)) catch-all
```''',
    "flask": '''```python
# in the module that builds your Flask app
from ava.surface import bp
app.register_blueprint(bp)
```''',
    "express": '''```js
// in your Express app
import { avaSurface } from './ava/surface.mjs';
app.use(avaSurface());   // BEFORE any express.static catch-all
```''',
    "stdlib": '''No framework needed — the surface is its own tiny server. Run it as a
sidecar next to your app:

```bash
python ava/surface.py        # serves /tools + /call + /health on port __PORT__
```

Call into your app from the tool handlers however fits (imports, HTTP, files).''',
}


def _render(app_id: str, label: str, framework: str, port: int, ui: bool) -> dict:
    """{relative path: content} for one scaffold."""
    env = re.sub(r"[^A-Z0-9]+", "_", app_id.upper())
    subs = {
        "__ID__": app_id,
        "__LABEL__": label,
        "__PORT__": str(port),
        "__FRAMEWORK__": framework,
        "__ENV_PORT__": f"{env}_SURFACE_PORT",
        "__ENV_TOKEN__": f"{env}_TOKEN",
    }
    if framework == "express":
        surface_name, surface = "surface.mjs", _EXPRESS_SURFACE
    else:
        surface_name = "surface.py"
        surface = _PY_CORE + {"fastapi": _FASTAPI_TAIL, "flask": _FLASK_TAIL,
                              "stdlib": _STDLIB_TAIL}[framework]
    readme = (_README
              .replace("__WIREUP__", _WIREUPS[framework])
              .replace("__SURFACE_FILE__", f"ava/{surface_name}"))
    manifest = _MANIFEST.replace("__UI_BLOCK__", _UI_ON if ui else _UI_OFF)
    files = {
        f"ava/{surface_name}": surface,
        "ava/connector.yaml": manifest,
        "ava/README-AVA.md": readme,
    }
    if framework in ("fastapi", "flask"):
        files["ava/__init__.py"] = ""     # so `from ava.surface import …` works
    out = {}
    for path, content in files.items():
        for key, val in subs.items():
            content = content.replace(key, val)
        out[path] = content
    return out


def create(app_id: str, framework: str = "fastapi", port: int = 9000,
           out_dir: str = ".", ui: bool = False, label: str | None = None) -> list[str]:
    """Write the scaffold into <out_dir>/ava/. Refuses to overwrite existing
    files (your edits are yours). Returns the written paths."""
    if not _ID_RE.match(app_id):
        raise ValueError("id must be 2-32 chars: a-z 0-9 _ - (starting with a letter)")
    if framework not in FRAMEWORKS:
        raise ValueError(f"framework must be one of: {', '.join(FRAMEWORKS)}")
    files = _render(app_id, label or app_id.replace("-", " ").replace("_", " ").title(),
                    framework, int(port), ui)
    clashes = [p for p in files if os.path.exists(os.path.join(out_dir, p))]
    if clashes:
        raise FileExistsError("refusing to overwrite: " + ", ".join(sorted(clashes)))
    written = []
    for path, content in files.items():
        full = os.path.join(out_dir, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(full)
    return written
